{% set name = "treon" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/treon-{{ version }}.tar.gz
  sha256: 6c31a1701036ee8a746adcc9ca59640269c01e887ea13ccc675680d39705d4f4

build:
  number: 0
  noarch: python
  entry_points:
    - treon = treon.treon:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docopt
    - jupyter
    - jupyter_client
    - nbconvert
    - python >=3.6

test:
  imports:
    - treon
  commands:
    - pip check
    - treon --help
  requires:
    - pip

about:
  home: https://github.com/reviewNB/treon
  summary: Testing framework for Jupyter Notebooks
  license: MIT
  license_file: LICENSE
  description: |
    Treon allows you to run notebook top to bottom and flags execution errors.
     It runs all unittests and doctests present in your notebook code cells. You
     can start testing notebooks without writing a single line of test code.
     Treon also enable multithreaded execution for quickly testing a set of
     notebooks. It executes every Notebook in a fresh kernel to avoid hidden
     state problems. Because treon is a command line tool itcan be used easily
     in any Continuous Integration (CI) system.


extra:
  recipe-maintainers:
    - thewchan
